### PR TITLE
feat: add event types to populate instructor dashboard (FC-0033)

### PR DESCRIPTION
**Pull request by SoryRawyer**
This PR adds event types (and updates existing events) to match what is currently used by the instructor dashboard. The new events are: video completed and transcript enabled/disabled. The existing problem check event needed a different verb_id.
The data generated by this tool should now produce enough data to populate each graph in the instructor dashboard as it currently exists (except for the watched video segments chart, which requires a specific pattern of data that I don't think is generated by this application).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]
This is great, thanks!

**Comment by bmtcril** [comment]
Can you bump the version here? https://github.com/openedx/xapi-db-load/blob/main/xapi_db_load/__init__.py then I can just merge and release.

**Comment by openedx-webhooks** [comment]
@SoryRawyer 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xapi-db-load&entry.867055334=https://github.com/openedx/xapi-db-load/pull/52&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2023-08-29+16:03&entry.1917517419=2023-08-29+19:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bmtcril** [comment]
All set, published as 0.8 if you want to update the aspects plugin!

**Pull request merged**
